name: CI

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - readme.md
  pull_request:
    paths-ignore:
      - readme.md
  workflow_dispatch:

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      # Visual Studio 2022 version 17.14.2 uses clang-format.exe version 19.1.5 
      - name: Install clang-format
        run: |
          run: sudo apt install -y clang-format-18

      - name: Run clang-format
        run: |
          find . \( -name '*.h' -o -name '*.cpp' \) ! -name 'directinput_scancodes.h' ! -name 'sha3.*' ! -name 'cpp.*' ! -name 'json.*' | xargs clang-format -Werror --dry-run

  build-wxwidgets:
    needs: formatting-check
    runs-on: windows-latest

    env:
      WX_VERSION: 3.2.8
      WXWIN: C:\wxWidgets

    steps:
      - name: Check wxWidgets cache
        uses: actions/cache@v4
        id: wx-cache
        with:
          path: C:\wxWidgets
          key: wxwidgets-${{ env.WX_VERSION }}-release-x64
          lookup-only: true

      - name: Setup wxWidgets cache
        if: steps.wx-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: C:\wxWidgets
          key: wxwidgets-${{ env.WX_VERSION }}-release-x64

      - name: Download wxWidgets
        if: steps.wx-cache.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest -Uri "https://github.com/wxWidgets/wxWidgets/releases/download/v${{ env.WX_VERSION }}/wxWidgets-${{ env.WX_VERSION }}.zip" -OutFile "$env:TEMP\wx.zip"
          Expand-Archive -Path "$env:TEMP\wx.zip" -DestinationPath "C:\wxWidgets"

        # https://github.com/actions/runner-images/blob/main/images/windows/Windows2025-Readme.md
        # Visual Studio Enterprise
        # Version 2022 17.14.36518.9
        # C:\Program Files\Microsoft Visual Studio\2022\Enterprise
      - name: Visual Studio 17
        if: steps.wx-cache.outputs.cache-hit != 'true'
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: '[17.1,18.0)'

      - name: Build wxWidgets (Release x64)
        if: steps.wx-cache.outputs.cache-hit != 'true'
        run: |
          msbuild "C:\wxWidgets\build\msw\wx_vc17.sln" /p:Configuration=Release /p:Platform=x64 /m
